### ISSUE TITLE
Remove dgram from dependencies in package.json

### ISSUE THREAD

**Issue by heyphets** [drachtio/rtpengine-client#11]
Hi Dave, 

The dgram package is held by npm (https://www.npmjs.com/package/dgram) and there are warnings thrown by npm when trying to install rtpengine-client.  It shouldn't be necessary to have it in package.json as it's a core module.

**Comment by davehorton** [comment]
I don't see it in [package.json](https://github.com/davehorton/rtpengine-client/blob/master/package.json) ?

**Comment by heyphets** [comment]
Ah, sorry about that. Looks like I need to update my dependencies to use later version of rtpengine-client.
