### ISSUE TITLE
ng commands

### ISSUE THREAD

**Issue by spointer** [drachtio/rtpengine-client#5]
Hi,
rtpengine supports play/stop media ng commands but it seems rtpengine-client does not support those.
Do you have any plans to support these commands?

**Comment by davehorton** [comment]
thanks and good point.  I will add these in next few days (if you have aleady done feel free to give me a PR!)

**Comment by spointer** [comment]
Hi,
I added just playMedia / stopMedia commands to your client.js commands array for test and i have confirmed it works well. (using the rtpengine docker you've made)

**Comment by davehorton** [comment]
can you give me a PR for those changes?  That would be great

**Comment by davehorton** [comment]
thanks!  merged your PR
