### ISSUE TITLE
Add uuid as a dependency

### ISSUE THREAD

**Issue by joelact** [drachtio/rtpengine-client#8]
When installing the package using production mode (`npm i --production`) the uuid dependency is missing, because when I start the application it says that it can't found uuid/v4. 

So I look at the package.json and saw that uuid is missing from the dependencies key.

@davehorton could you update the dependencies for the project? Or give me instructions on which version to add in the pull request?

**Comment by davehorton** [comment]
thanks please update to rtpengine-client@0.1.0
